@KucniSavetBackend_HostAddress = http://localhost:5210
@ID = a/33-A

### Create User
# @name CreateUser
POST {{KucniSavetBackend_HostAddress}}/api/user
Accept: application/json
Content-Type: application/json

{
    "email": "korisnik@imejl.rs",
    "name": "Gal Kapucino",
    "image": ""
}

### Get all Users
GET {{KucniSavetBackend_HostAddress}}/api/user
Accept: application/json

### Get one User
GET {{KucniSavetBackend_HostAddress}}/api/user/{{CreateUser.response.body.id}}

### Get one User - NOTFOUND
GET {{KucniSavetBackend_HostAddress}}/api/user/loremipsum

### Update User
PUT {{KucniSavetBackend_HostAddress}}/api/user/{{CreateUser.response.body.id}}
Accept: application/json
Content-Type: application/json

{
    "id": "{{CreateUser.response.body.id}}",
    "email": "korisnik@imejl.rs",
    "name": "Kael Kestis",
    "image": null
}

### Delete User
DELETE {{KucniSavetBackend_HostAddress}}/api/user/{{CreateUser.response.body.id}}