@KucniSavetBackend_HostAddress = http://localhost:5210
@ID = a/33-A

### Create household
# @name CreateHousehold
POST {{KucniSavetBackend_HostAddress}}/api/household
Accept: application/json
Content-Type: application/json

{
    "name": "Kuca Mirkovic"
}

### Get one Household
GET {{KucniSavetBackend_HostAddress}}/api/household/{{CreateHousehold.response.body.id}}

### Get one Household - NOTFOUND
GET {{KucniSavetBackend_HostAddress}}/api/household/loremipsum